const INTERNAL_SERVER_ERROR = 500;
const BAD_REQUEST_ERROR = 400;
const NOT_FOUND = 404;
const CONFLICT_ERROR = 409;

module.exports = {
  INTERNAL_SERVER_ERROR,
  BAD_REQUEST_ERROR,
  NOT_FOUND,
  CONFLICT_ERROR,
};
